run mvn package instead of test for correct module order

diff --git a/.github/workflows/maven-manual.yml b/.github/workflows/maven-manual.yml
--- a/.github/workflows/maven-manual.yml
+++ b/.github/workflows/maven-manual.yml
@@ -33,7 +33,8 @@ jobs:
     - name: Maven tests
       run: |
         export MAVEN_HOME=/usr/bin/mvn
-        mvn test -fn --file Realization/backend/aggregator/pom.xml -Dspring.profiles.active=test | perl -pe 'END { exit $status } $status=1 if /BUILD FAILURE/;'
+        # mvn test -fn --file Realization/backend/aggregator/pom.xml -Dspring.profiles.active=test | perl -pe 'END { exit $status } $status=1 if /BUILD FAILURE/;'
+        mvn -B package -fn --file Realization/backend/aggregator/pom.xml -Dspring.profiles.active=test | perl -pe 'END { exit $status } $status=1 if /BUILD FAILURE/;'
     - name: Upload logs
       uses: actions/upload-artifact@v3
       if: failure()
