grep result from output

diff --git a/.github/workflows/maven-manual.yml b/.github/workflows/maven-manual.yml
--- a/.github/workflows/maven-manual.yml
+++ b/.github/workflows/maven-manual.yml
@@ -31,6 +31,6 @@ jobs:
       with:
         java-version: 11
     - name: Maven tests
-      run: mvn test --fail-at-end --file Realization/backend/aggregator/pom.xml -Dspring.profiles.active=test
-      #run: mvn test -fn --file Realization/backend/aggregator/pom.xml -Dspring.profiles.active=test | perl -pe 'END { exit $status } $status=1 if /BUILD FAILURE/;'
+      #run: mvn test --fail-at-end --file Realization/backend/aggregator/pom.xml -Dspring.profiles.active=test
+      run: mvn test -fn --file Realization/backend/aggregator/pom.xml -Dspring.profiles.active=test | perl -pe 'END { exit $status } $status=1 if /BUILD FAILURE/;'
     
